sudo: required
services:
  - docker

before_install:
  - docker image build -t yravinderkumar33/travissetup .

script: 
  - docker container run yravinderkumar33/travissetup npm run test --watch=false